### ISSUE TITLE
可以加上右侧和左侧的点击事件

### ISSUE THREAD

**Issue by lxlnihao** [CXTretar/CXLinkageSheetDemo#1]
右侧加上点击事件就更好了

**Comment by CXTretar** [comment]
@lxlnihao 我添加2个代理点击事件，可以更新cocoapods或者下载demo查看，希望能帮助到你。

**Comment by lxlnihao** [comment]
多谢 和我自己加的差不多 我是在你的item上加了一个新button,知道这样不好 你的代码还是你自己清楚,写的不错 谢谢

**Comment by CXTretar** [comment]
直接添加UIButton也可以，代码是公开的，你可以随意使用和更改，不用客气。
